### ISSUE TITLE
Setting up testing envirionment

### ISSUE THREAD

**Issue by stevavoliajvar** [alexej996/xmppmirror#4]
Ideally there should be testing config so when someone is making changes to code can make sure they are working. Currently slix complains about not being able to parse JID for example. I suggest making couple of accounts and rooms on some servers and using them for testing. Problem is password sharing so instead of that we can add small tutorial of test environment setup into README.md ?

**Comment by alexej996** [comment]
Just finished adding a test directory. Testing can now be done with test.sh script using ejabberd docker container.
